#!/usr/bin/env python3
import colors as c
import random

print('welcome to the magic eightball.')

answers = ["yes.","maybe.","no.","obiously","???","outlook not so good","reply hazy try again",
"not in a million years.","I have no idea","It is certain.",
"MEH","yes defenetly","better not tell you now","dear god no"]
def ask(prompt):
    answer = input('> ' + c.red).strip().lower()
    return answer

try:

    while True:
       question = ask("-->")  
       if  "death" in question or "die" in question:
            print(c.base3 + "I will not answer that")
       elif "???" in question:
            print("I dont know what you just said")
       else:    
            answer = random.choice(answers)
            print(answer)

except KeyboardInterrupt:
    print("see you later.")
    exit()



















