#!/usr/bin/env python

import time
import colors as c
print(c.clear)

snake = '''
 (        )              )       
 )\ )  ( /(   (       ( /(       
(()/(  )\())  )\      )\()) (    
 /(_))((_)\((((_)(  |((_)\  )\   
(_))   _((_))\ _ )\ |_ ((_)((_)  
/ __| | \| |(_)_\(_)| |/ / | __| 
\__ \ | .` | / _ \    ' <  | _|  
|___/ |_|\_|/_/ \_\  _|\_\ |___| 
                                 
'''


for count in range(5):

    for badgers in range (12):
        print(c.blue + "badgers!")
        time.sleep(0.4)

    for mushroom in range (2):
        print(c.magenta + "mushroom")
        time.sleep(0.4)
    
print(snake)    


















