#!/usr/bin/env python3

import colors as c

print(c.clear + c.blue + '''
     Who shall cross the bridge of death 
     must answer me three questions three           
     'Ere the other side he see.
''' + c.reset)      

def prompt(question):
    print(c.red + question + c.reset)
    answer = input('>' + c.base3).lower().strip()
    print(c.reset)
    return answer

def live():
        print('go ahead across the bridge')

def die():
    print('swim with the ACID!!!!!')

name = prompt('what is your name?')
quest = prompt('What is your quest?')

if name in ['lancelot','galahad']:
    color = prompt('what is your favorite color')
    if color == 'blue':
        live()
    else:
        die()

elif name == 'robin':
    capital = prompt ('What is the capital of Assyria?')
    if capital in ['assur','ashur']:
        live()
    else:
        die()

elif name == 'arthur':
    speed = prompt('What is the air speed velocity of an unladen swallow?')
    if speed == '24mph':
        live()
    elif 'african or european swallow' in speed:
        print('Bridgekeeper dies.')
        live()
    else:
        die()




