#!/usr/bin/env python3

import colors as c
print(c.clear)

sides = [1,2,3,4,5,6]

for side in sides:
    print("side:",side)


#while n < 6:
#    print("n:", n)
#    print("side:",sides[n])
#    n += 1


