#!/usr/bin/env python3
import colors as c

print("do you like waffles")
waffles = input(" > ")
if waffles =="yes":
    print(":D")
else:
    print("dont worry,I dont like waffles either...")
print("do you like pancakes")
pancakes = input(" > ")
if pancakes =="yes" :
    print(":D :D")
else:
    print("WHAT??!!")












